version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "log-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18przlb4dnncp"
s3_prefix = "log-service"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
