Transform: AWS::Serverless-2016-10-31
AWSTemplateFormatVersion: "2010-09-09"

Description: "Infrastructure for DIY log handler"

Resources:
  GetLogsLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getLogs    
      CodeUri: ../controllers/getLogs
      Handler: getLogs.handler
      Runtime: nodejs14.x
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        GetLogs:
          Type: Api
          Properties:
            Path: /logs
            Method: GET    

  TriggerLogs:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: triggerLogs    
      CodeUri: ../controllers/triggerLogs
      Handler: triggerLog.handler
      Runtime: nodejs14.x
      Policies:
        - AmazonDynamoDBFullAccess      
      Events:
        GetLogs:
          Type: Api
          Properties:
            Path: /trigger
            Method: GET

  LogTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Logs
      AttributeDefinitions:
        - 
          AttributeName: 'requestId'
          AttributeType: S
      KeySchema:
        - 
          AttributeName: 'requestId'
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5             